# Numpy Indroduction

In [1]:
#pip install numpy

In [2]:
import numpy as np

# What is an array?
An array is a data structure that stores elements of the same type in a contiguous block of memory. It is a collection of elements, where each element is identified by its index or position. In Python, arrays are implemented using the NumPy library, which provides a powerful N-dimensional array object.

Arrays can be one-dimensional or multi-dimensional, and can be indexed and sliced using square brackets. They can also be reshaped and manipulated using a wide range of NumPy functions.

In the context of data science and machine learning, arrays are commonly used to store and manipulate data, as they provide efficient storage and computation. They are especially useful when working with large datasets, as they can be efficiently stored in memory and manipulated using vectorized operations.

In [3]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [4]:
a.shape

(6,)

In [5]:
# two dimenstional
a2=a[np.newaxis,:]
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [6]:
a2=a[:,np.newaxis]
print(a2)

a2.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [7]:
# three dimenshional
a3=a2[np.newaxis,:]
print(a3)

a3.shape

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]]]


(1, 6, 1)

# why do have 1D,2D,3D array and where we need them in DS?

# creating Array with Numpy

In [8]:
a=np.array([1,2,3,4,5,6,7])
b=np.array([(1,2,3,4,5,6,7),(4,5,6,7,8,9,10)])

In [9]:
type(a)# type of array

numpy.ndarray

In [10]:

print(a)
a.shape

[1 2 3 4 5 6 7]


(7,)

In [11]:
a.dtype # data type of array elements

dtype('int32')

In [12]:
print(b)
b.shape

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


(2, 7)

# initialize arrays

In [13]:
zeros=np.zeros((4,5)) # (rows,columns)
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
ones=np.ones((2,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
full=np.full((2,5),5)
full

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [16]:
identity=np.eye(5)# creatng an identity matrix
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
identity.dtype

dtype('float64')

# Array attributes

In [18]:
a.shape# shape of array

(7,)

In [19]:
len(a)# give us the length of elements in array

7

In [20]:
a.ndim

1

In [21]:
b.ndim# give  us the dimenstion of array

2

In [22]:
a.size# give us the number of elements in array

7

# basic operations

In [23]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
g=a-b# subtraction
g

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3, -3]])

In [25]:
#addition
h=a+b
h

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [26]:
# another method of addition
h1=np.add(a,b)
h1


array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [27]:
# multiplications
i=a*b
i

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 70]])

In [28]:
#division
j=a/b
j

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667, 0.7       ]])

In [29]:
# squre of each elements
k=a**2
k

array([ 1,  4,  9, 16, 25, 36, 49])