# Numpy (part-2)

In [1]:
import numpy as np

In [2]:
empty=np.empty((2,4))
print(empty)
print("-----------------")
print(empty[1])#print with indexing

[[4.67296746e-307 1.69121096e-306 6.23058707e-307 2.22526399e-307]
 [6.23053614e-307 7.56592338e-307 9.34588061e-307 3.62651150e-317]]
-----------------
[6.23053614e-307 7.56592338e-307 9.34588061e-307 3.62651150e-317]


In [3]:
np.arange(23)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [4]:
even=np.arange(0,23,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [5]:
#array of odd number from 0 to 23
odd=np.arange(1,23,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [6]:
# specific difference between number
diff=np.arange(0,23,.515)
diff

array([ 0.   ,  0.515,  1.03 ,  1.545,  2.06 ,  2.575,  3.09 ,  3.605,
        4.12 ,  4.635,  5.15 ,  5.665,  6.18 ,  6.695,  7.21 ,  7.725,
        8.24 ,  8.755,  9.27 ,  9.785, 10.3  , 10.815, 11.33 , 11.845,
       12.36 , 12.875, 13.39 , 13.905, 14.42 , 14.935, 15.45 , 15.965,
       16.48 , 16.995, 17.51 , 18.025, 18.54 , 19.055, 19.57 , 20.085,
       20.6  , 21.115, 21.63 , 22.145, 22.66 ])

In [7]:
lin=np.linspace(0,20,num=10)
lin

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [8]:
lin.dtype

dtype('float64')

In [9]:
# define the data type of array
x=np.arange(0,22.6,1.5,dtype=np.int64)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int64)

# **assingments:** what is the different betwwen int32,64,16.....in ka kia matlb hy? why does we use one and not the other one?

In [10]:
# sorting and array
arr=np.array([2,1,5,3,7,6,8])
arr

array([2, 1, 5, 3, 7, 6, 8])

In [11]:
np.sort(arr)


array([1, 2, 3, 5, 6, 7, 8])

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [13]:
c=np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

# concatenate 2D array

In [14]:
x = np.array([[1, 2], [3, 4]])#2x2 array
y = np.array([[5, 6]])# 1x2

In [15]:
z=np.concatenate((x,y),axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
w=np.array([[5,1],[7,1]])
z1=np.concatenate((x,w),axis=0)#axis=1
z1

array([[1, 2],
       [3, 4],
       [5, 1],
       [7, 1]])

In [17]:
# create 3D array
a1= np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

print(a1)
a1.ndim

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


3

In [18]:
len(a1)

3

In [19]:
a1.dtype

dtype('int32')

In [20]:
a1= np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7],
                           [4, 5, 6, 7]]])
a1.shape

(1, 3, 4)

In [21]:
#reshape array
a2=a1.reshape(6,2)
a2.shape

(6, 2)

In [22]:
a2.reshape(3,1,4)

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[4, 5, 6, 7]]])

In [23]:
# creTE 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape

(8,)

In [24]:
# convert that into 2D array
b=a[np.newaxis,:].shape
b

(1, 8)

In [25]:
c=a[:,np.newaxis]
c.shape

(8, 1)

# indexing and slicing

In [26]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
a[-4:-2]

array([5, 6])

In [28]:
a[2:5]

array([3, 4, 5])

In [29]:
b = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
b[0]

array([1, 2, 3, 4])

In [31]:
b[b<2]

array([1])

In [32]:
b[b>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
b[b%2==0]# filter even number

array([ 2,  4,  6,  8, 10, 12])

In [34]:
b[b%2==1]# filter odd number

array([ 1,  3,  5,  7,  9, 11])

In [35]:
# use two conditions
b[(b>2)&(b<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
# use there condition and filter the array
b[(b>2)&(b<11)&b%2==0]


array([ 1,  2,  4,  6,  8, 10, 11, 12])

In [37]:
b[(b>2)|(b<11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# google search numpy
* documentation
*  * getting started
